version: "3"
services:
#Nginx Container
    nginx:
        image: nginx:stable-alpine
        ports:
            - "5000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#Express API Container
    express-api:
        build: .
        env_file:
            - ./.env
        depends_on:
            - postgres-database

#Postgres DB Container
    postgres-database:
        image: postgres
        volumes:
            - postgres-db:/var/lib/postgresql/data

#Redis Container
    redis:
        image: redis
volumes:
    postgres-db: