version: "3"
services:
    express-api:
        build:
            context: .
            args:
                NODE_ENV: test
        volumes:
            - ./:/app:ro
            - /app/node_modules
        env_file:
            - ./.env
        command: npm run test