version: "3"
services:
    express-api:
        build:
            context: .
            args:
                NODE_ENV: development
        command: bash -c "cd src/db && npx knex migrate:latest && cd ../.. && npm run dev"
       
        volumes:
            - ./:/app:ro
            - /app/node_modules
        env_file:
            - ./.env
        
