version: "3"
services:
    express-api:
        build:
            context: .
            args:
                NODE_ENV: production
        env_file:
            - ./.env
        command: node index.js