version: "3"
services:
#Express API Container
    express-api:
        build: .
        env_file:
            - ./.env
        depends_on:
            - postgres-database
        environment:
            PORT: 5000
        ports:
            - '5000:5000'

#Postgres DB Container
    postgres-database:
        image: postgres
        volumes:
            - postgres-db:/var/lib/postgresql/data

#Redis Container
    redis:
        image: redis
volumes:
    postgres-db: