# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.USER}}
          
          script: |
            cd test
            cd express-docker
            git pull

 
   
 
      
  
