# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run :  sudo apt-get update
    - name: install lftp
      run: sudo apt-get install lftp
    - name: coin
      run : lftp sftp://root:0451The_Bioshock_Within@178.62.217.57
    - name: bla
      run : pwd
      
  
